### ISSUE TITLE
Add more worker information to the task queue describe

### ISSUE THREAD

**Issue by mfateev** [temporalio/cli#119]
Currently, DescribeTaskQueueResponse contains more information that is displayed by `tctl tq describe`. I think it would be nice to show all of it in UI/CLI. 

An additional piece of information I would add is the worker binary checksum or any other worker version related information. It would allow troubleshooting situations when an old worker is still polling a service.

**Comment by edmondop** [comment]
Speaking with @yiminc I understood this is blocked, can we maybe link the blocking issue here if there's one?

**Comment by josh-berry** [comment]
I think the JSON output includes everything we can meaningfully provide. The latest version of Versioning does not include binary checksums etc., just the build ID. But if something is missing, please feel free to re-open.
