### ISSUE TITLE
[Feature Request] Set `system.forceSearchAttributesCacheRefreshOnRead=true` by default for dev server

### ISSUE THREAD

**Issue by bergundy** [temporalio/cli#138]
While clearly not a production flag, it improves the experience local development experience and should be the default.

Note that there's a regression in the registration delay for search attributes for SQL based persistence in 1.20 reported [here](https://github.com/temporalio/temporal/issues/4017).

**Comment by feedmeapples** [comment]
We already set this right? https://github.com/temporalio/cli/blob/main/server/options.go#L166

**Comment by bergundy** [comment]
Should’ve looked, I forgot we have this
