### ISSUE TITLE
[Bug] Help output includes markdown gobbledygook

### ISSUE THREAD

**Issue by Sushisource** [temporalio/cli#151]
In the `defs-cmds.go` file (and perhaps elsewhere?) there's markdown that is clearly intended for the docs site that we dump to the console as part of help output. This is clearly undesirable. I imagine the best option here is to strip these out and instead include a link to the docs page for the command at the end of the usage output.

EX:

    λ  ./temporal task-queue describe --help
    NAME:
       temporal task-queue describe - Describes the Workers that have recently polled on this Task Queue.
    
    USAGE:
       The `temporal task-queue describe` command provides [poller](/application-development/worker-performance#poller-count) information for a given [Task Queue](/concepts/what-is-a-task-queue).
    
       The [Server](/concepts/what-is-the-temporal-server) records the last time of each poll request.
       Should `LastAccessTime` exceeds one minute, it's likely that the Worker is at capacity (all Workflow and Activity slots are full) or that the Worker has shut down.
       [Workers](/concepts/what-is-a-worker) are removed if 5 minutes have passed since the last poll request.
    
       Use the options listed below to modify what this command returns.
       Make sure to write the command as follows:
       `temporal task-queue describe [command options]`

**Comment by bergundy** [comment]
Resolved in #167

**Comment by bergundy** [comment]
We're still rendering markdown on non-leaf commands.

**Comment by Quinn-With-Two-Ns** [comment]
This is resolved in the rewrite
