### ISSUE TITLE
[Bug] Valid JSON input causes error

### ISSUE THREAD

**Issue by pvsone** [temporalio/cli#159]
### What are you really trying to do?
I am trying to execute a workflow and pass JSON input via the `--input` option to the `temporal workflow execute` command

### Describe the bug
The following command, (incorrectly) results in an error
```
temporal workflow execute \
    --task-queue workshop \
    --type example01 \
    --input '{"A":1,"B":2}'
Error: input is not valid JSON: unexpected end of JSON input
```

### Minimal Reproduction
See above, the JSON input `'{"A":1,"B":2}'` is not accepted by the `temporal workflow execute` command.  

However the same input is accepted by `tctl workflow run`
```
tctl workflow run \
    --taskqueue workshop \
    --workflow_type example01 \
    -i '{"A":1,"B":2}'
...
Result:
  Run Time: 1 seconds
  Status: COMPLETED
  Output: [{"Result":3}]
```

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: `temporal version 0.6.0 (server 1.20.0) (ui 2.11.0)`

**Comment by bergundy** [comment]
Fixed in 0.7.0.
