### ISSUE TITLE
[Feature Request] Clarify what the default response is and what happened

### ISSUE THREAD

**Issue by lorensr** [temporalio/cli#163]
### Is your feature request related to a problem? Please describe.

When I see a prompt like

` Continue? Y/N`

I'm unsure what will happen when I hit return (without typing a letter). And in the case of 

`temporal workflow terminate  -q 'ExecutionStatus="Running"' --reason clear`

I don't get any output saying what happened.

### Describe the solution you'd like

Some indication of the default choice, like maybe a lowercase y if N is default:

`Will start a batch job operating on 120 Workflow Executions. Continue? y/N`

And output in the No case, like:

`command canceled`

(And not just for `workflow terminate`, but for all confirmation dialogs.)

### Additional context

![image](https://user-images.githubusercontent.com/251288/226802537-feebbc8e-1013-40bd-a0d1-c76aa1c4d6e2.png)

**Comment by feedmeapples** [comment]
addressed this here https://github.com/temporalio/cli/commit/636fe2327b99b0da1d495b157edcb58150aa042a
