### ISSUE TITLE
[Feature Request] Unified dev Server & UI --config'uration

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/cli#184]
### Is your feature request related to a problem? Please describe.
Server `--config` option, that was a directory expecting `temporal.yaml` and `temporal-ui.yaml` files, was not intuitive. It [was removed](https://github.com/temporalio/cli/pull/183) and now there is no option to configure server and UI (aside from the configs exposed as CLI --flags)

### Describe the solution you'd like
Support configuring Temporal server and UI with a single .yaml config file set as `temporal server start-dev --config /path/to/temporal-config.yaml`

Config's template may look as following:

* Temporal  server's existing config https://github.com/temporalio/temporal/blob/master/docker/config_template.yaml
* Add a new `ui:` entry
* `ui:` entry may match UI [config template](https://github.com/temporalio/ui/blob/4e5ab26534270d3ba3b947ccb8675fe4121e3d93/server/docker/config-template.yaml)

🧵🧵🧵 for discussion :point_down:

**Comment by feedmeapples** [comment]
Config's template may look as following:

- Temporal  server's existing config https://github.com/temporalio/temporal/blob/master/docker/config_template.yaml
- We add a new `ui:` entry
- `ui:` entry may match UI config template https://github.com/temporalio/ui/blob/main/server/docker/config_template.yaml

**Comment by feedmeapples** [comment]
cc @jlegrone @bergundy @dnr @cretz @yiminc

**Comment by bergundy** [comment]
@feedmeapples we should look at redesigning this from first principles.
Maybe your proposal for passthrough configs is good enough but there may be some overlap between the different services and configs that are irrelevant in single binary context.
If we go for a redesign, the configs we expose should be well documented and follow a uniform convention.
I would try out some different options and seeing what feels right.

**Comment by josh-berry** [comment]
I think if folks need custom configs, they should probably be using the actual server and not the dev-server. Going to close this, but I'm willing to reconsider if there's customer/user interest.
