### ISSUE TITLE
[Bug] Can't schedule workflows with parameters from CLI

### ISSUE THREAD

**Issue by maelropars** [temporalio/cli#208]
### What are you really trying to do?

Scheduling a workflow expecting parameters
transfer(fromAccountId: string, toAccountId: string, referenceId: string, amountCents: number)

### Describe the bug

None of the proposed options to create a schedule with multiple inputs works 
- sending multiple JSON, one per param, with multiple --input
- sending a JSON with multiple params using --input
- sending a JSON with multiple params using --input-file
-  sending a concatenated JSON (one JSON per line per param) using --input-file

Note : it works fine using the API.

### Minimal Reproduction

% temporal schedule create -s "myrec22" -t "moneytransfer-typescript" -w "transfer_auto" --workflow-type transfer  --interval 20s --input "{\"fromAccountId\": \"titi\",\"toAccountId\": \"toto\",\"referenceId\": \"bla\",\"amountCents\": 250}"
Schedule created

Input of workflow
[
  {
    "amountCents": 250,
    "fromAccountId": "titi",
    "referenceId": "bla",
    "toAccountId": "toto"
  }
]
In the workflow, amountCents is undefined (Typescript)

% cat ../tctl/schedule_params.json 
[{"fromAccountId": "titi"},{"toAccountId": "toto"},{"referenceId": "bla"},{"amountCents": 251}]

%temporal schedule create -s "myrec4" -t "moneytransfer-typescript" -w "transfer_auto" --workflow-type transfer  --interval 20s --input-file ../tctl/schedule_params.json
Schedule created

Workflow input
[
  [
    {
      "fromAccountId": "titi"
    },
    {
      "toAccountId": "toto"
    },
    {
      "referenceId": "bla"
    },
    {
      "amountCents": 251
    }
  ]
]
In the workflow, amountCents is undefined (Typescript)

%temporal schedule create -s "myrec2" -t "moneytransfer-typescript" -w "transfer_auto" --workflow-type transfer  --interval 20s --input "{\"fromAccountId\": \"titi\"}" --input "{\"toAccountId\": \"toto\"}" --input "{\"referenceId\": \"bla\"}" --input "{\"amountCents\": 250}"
Schedule created

Workflow input
[
  {
    "fromAccountId": "titi"
  },
  {
    "toAccountId": "toto"
  },
  {
    "referenceId": "bla"
  },
  {
    "amountCents": 250
  }
]
In the workflow, amountCents is undefined (Typescript)

% cat ../tctl/schedule_params.json
{"fromAccountId": "titi"}
{"toAccountId": "toto"}
{"referenceId": "bla"}
{"amountCents": 251}

%temporal schedule create -s "myrec4" -t "moneytransfer-typescript" -w "transfer_auto" --workflow-type transfer  --interval 20s --input-file ../tctl/schedule_params.json
Error: input is not valid JSON: invalid character '{' after top-level value
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/temporalio/cli/app.HandleError(0x18?, {0x107253e60, 0x14000361020})
	/Users/maelropars/CLI/app/app.go:78 +0x13c
github.com/urfave/cli/v2.(*App).handleExitCoder(0x140008ab900?, 0x14000275c00?, {0x107253e60?, 0x14000361020?})
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:446 +0x3c
github.com/urfave/cli/v2.(*Command).Run(0x140008ab900, 0x14000c6d1c0, {0x1400086bee0, 0xd, 0xd})
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:273 +0x808
github.com/urfave/cli/v2.(*Command).Run(0x1085a9b00, 0x14000c6d080, {0x140001ce540, 0xe, 0xe})
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:264 +0x9fc
github.com/urfave/cli/v2.(*Command).Run(0x140008b2f00, 0x14000874e00, {0x1400004e0f0, 0xf, 0xf})
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:264 +0x9fc
github.com/urfave/cli/v2.(*App).RunContext(0x140001e43c0, {0x107271880?, 0x14000054070}, {0x1400004e0f0, 0xf, 0xf})
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:333 +0x5dc
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/maelropars/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:310
main.main()
	/Users/maelropars/CLI/cmd/temporal/main.go:14 +0x48

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.20.2 ; CLI 0.8.0 
- Are you using Docker or Kubernetes or building Temporal from source? latest from docker-compose

**Comment by feedmeapples** [comment]
ty, looking into this

**Comment by feedmeapples** [comment]
were you able to figure this out?

if not try like this 

```
temporal schedule create -s 1 -w 1 -t 1 --workflow-type 1 -i '{"fromAccountId": "titi"}' -i '{"toAccountId": "toto"}' -i '{"referenceId": "bla"}' -i '{"amountCents": 251}'
```
