### ISSUE TITLE
[Bug] namespace update - update ns retention not working

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/cli#209]
temporal -v
temporal version 0.8.0 (server 1.20.1) (ui 2.13.3)
running server version 1.20.1 on local docker (tried with minikube too)

command 
temporal operator namespace update default --retention 3

does not update the namespace retention, no error result of command is "Namespace default successfully updated."

works ok with tctl for example: 
tctl --ns default n u -rd 3

**Comment by sahilvv** [comment]
This bug is impacting our transition from tctl to temporal cli. Related command is also not working:
```
temporal operator namespace update temporal-system --email xxx --retention 90
```

**Comment by bergundy** [comment]
User reported on slack that this command was not setting email and retention either:
```
temporal operator namespace create test-cli --retention 10 --email abc@gmail.com
```

**Comment by feedmeapples** [comment]
working on this

**Comment by feedmeapples** [comment]
the namespace argument should come last. I think we should clarify this in docs and --help

```
temporal operator namespace update --email xxx --retention 90 temporal-system
```

**Comment by feedmeapples** [comment]
checking if we can make the argument positioned differently. Otherwise keeping the item open to detect misplaced namespace arg

**Comment by feedmeapples** [comment]
If namespace arg comes before the flags, the flags are ignored by urfave/cli and non of the fields are actually updated.

We can change the output of the command so it lists the fields that has actually changed:

before
```
temporal operator namespace update --email xxx --retention 90 default
Namespace default successfully updated.
```

after
```
temporal operator namespace update default --email xxx --retention 90
Namespace update changes implemented:

Field        Before    After    
Retention      1        90
Email                   xxx
```

**Comment by feedmeapples** [comment]
we can also detect that there are flags passed after the arg and throw an error saying to pass the arg the last
