### ISSUE TITLE
[Feature Request] Use codec server to convert textual input to payload and payload to text to display

### ISSUE THREAD

**Issue by bergundy** [temporalio/cli#22]
Right now remote codec is used to convert payloads -> payloads, this approach has limited flexibility and is restricted mostly to JSON input / output.

**Comment by josh-berry** [comment]
@bergundy Can you explain this one to me a little more? I didn't think codecs even supported converting to text—they are always payload-to-payload, no? Am I missing something?

**Comment by bergundy** [comment]
Looks like this is already addressed in the CLI rewrite. We can close as soon as it's merged.
Inputs are much more flexible, way beyond JSON.

**Comment by cretz** [comment]
Closing now as already handled in CLI rewrite (though yes, technically we haven't merged it to `main` yet).
