### ISSUE TITLE
[Feature Request] Env var for cert and key

### ISSUE THREAD

**Issue by lorensr** [temporalio/cli#253]
### Is your feature request related to a problem? Please describe.

Currently we only have env vars for paths to cert and key, but not the cert/key themselves. Which means if I don't want to have my certs in plaintext files, I can't use common env-var-based tools like `op run`:

https://developer.1password.com/docs/cli/reference/commands/run/#examples

### Describe the solution you'd like

Add:

```
TEMPORAL_CLI_TLS_CERT_BODY
TEMPORAL_CLI_TLS_KEY_BODY
```

or `_CONTENTS`?

Or rename all the existing env vars to `_FILE` and name these `TEMPORAL_CLI_TLS_KEY` (breaking).

**Comment by Sushisource** [comment]
Done in https://github.com/temporalio/cli/pull/484 as part of the cli rewrite
