### ISSUE TITLE
[Feature Request] Server local dev mode shouldn't have low persitence QPS limits

### ISSUE THREAD

**Issue by Sushisource** [temporalio/cli#255]
If you hammer away at the server in `start-dev` mode, you can semi-easily run into things like

"Unable to read search attributes types: Persistence Max QPS Reached."

We should automatically set quite high dynamic config value for these IMO. In dev mode, there's no need to limit damage like this and it's just annoying if you're trying to run something intense.

**Comment by feedmeapples** [comment]
good call, i've actually sent a PR for this https://github.com/temporalio/cli/pull/130 and never tested as it didn't seem like people run into this much. Wdyt about the PR?

**Comment by Sushisource** [comment]
@feedmeapples I would say let's merge it. Don't really see any meaningful downside here.
