### ISSUE TITLE
[Bug] Segmentation violation when running workflow list

### ISSUE THREAD

**Issue by fitialovks** [temporalio/cli#258]
### What are you really trying to do?
I am starting a development server in our CI system to run some tests. To check that the server is ready before starting the tests, I use `./temporal workflow list --address localhost:{port`} command with the selected port substituted. The idea is to check the exit code of the command and to proceed once I get a zero.

### Describe the bug
The command always fails in the CI with the following output.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x181efcc]

goroutine 1 [running]:
github.com/temporalio/tctl-kit/pkg/config.(*Config).EnvProperty(0x2601760?, {0x266d4ac, 0x7}, {0xc000bb65f8, 0x5})
	/home/runner/go/pkg/mod/github.com/temporalio/tctl-kit@v0.0.0-20230328153839-577f95d16fa0/pkg/config/config.go:89 +0x2c
github.com/temporalio/cli/env.loadEnv(0xc000d0c980)
	/home/runner/work/cli/cli/env/env.go:221 +0x22c
github.com/temporalio/cli/common.AddBeforeHandler.func1(0x2?)
	/home/runner/work/cli/cli/common/util.go:548 +0x4b
github.com/temporalio/cli/common.AddBeforeHandler.func1(0xc000dd2dc0?)
	/home/runner/work/cli/cli/common/util.go:542 +0x34
github.com/urfave/cli/v2.(*Command).Run(0xc000dd2dc0, 0xc000d0c980, {0xc000bb2330, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:211 +0x502
github.com/urfave/cli/v2.(*Command).Run(0x4720680, 0xc000d0c800, {0xc000d0c840, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:264 +0xcd7
github.com/urfave/cli/v2.(*Command).Run(0xc0008dedc0, 0xc000d0c680, {0xc0000500a0, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:264 +0xcd7
github.com/urfave/cli/v2.(*App).RunContext(0xc0005183c0, {0x3399900?, 0xc00005a068}, {0xc0000500a0, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:310
main.main()
	/home/runner/work/cli/cli/cmd/temporal/main.go:14 +0x45
```

Note that it works on my laptop running Ubuntu 22.04.

Upd: I believe, an absent `HOME` environment variable may be the culprit. An error message or a fallback would be a fix.

### Minimal Reproduction
Unfortunately, I cannot reproduce the environment we have in our cloud CI.

### Environment/Versions

* OS and processor: Linux, Ubuntu, amd64
* Temporal Version:

```
temporal --version
temporal version 0.9.0 (server 1.20.2) (ui 2.15.0)
```

* Are you using Docker or Kubernetes or building Temporal from source?
I am using the CLI binary from the official website.

### Additional context
Hopefully, this bug is obvious from the stack trace. Let me know if you need more details, I may be able to extract more information from our CI system.

**Comment by feedmeapples** [comment]
yes the logs seem to be enough. Should be a quick fix getting back shortly

**Comment by feedmeapples** [comment]
Are you use that `--env` flag was not set with your command? I believe it shouldn't reach `/home/runner/work/cli/cli/env/env.go:221` according to https://github.com/temporalio/cli/blob/f8c84edae78379ad3716ed51c84120c923db9388/env/env.go#L212

**Comment by fitialovks** [comment]
I am pretty confident that it was not. Here is my Python code
```python
subprocess.run(['./temporal', 'workflow', 'list', '--address', 'localhost:{}'.format(port)])
```

BTW we are now using `temporal operator cluster health` to check the development server startup in the tests. It seems to be more appropriate.

**Comment by Quinn-With-Two-Ns** [comment]
Testing I could not reproduce this on the CLI rewrite [branch](https://github.com/temporalio/cli/tree/cli-rewrite) I could not reproduce this be unsetting the `HOME` env variable

**Comment by marianosimone** [comment]
Just want to report that I'm facing the same error. If an environment is passed in, but it doesn't contain the `HOME` variable, the panic occurs.

I think it would be better to catch the error and explain what's going on instead.
