### ISSUE TITLE
[Bug] Prevent deleting default env

### ISSUE THREAD

**Issue by lorensr** [temporalio/cli#262]
### Describe the bug

Because once it's deleted, I can't set it:

```
t env delete default
Deleted env: default

t env set default.address localhost:7233
Error: env not found: default
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

**Comment by bergundy** [comment]
Hmm.. it should be okay to empty the contents of the default env.
In any case `temporal env set default.address localhost:7233` should not fail if the default env doesn't exist.

**Comment by lorensr** [comment]
I get the same

```
Error: env not found: default
```

when running most commands

**Comment by bergundy** [comment]
I got that too.
I think we can make an exception and treat missing default as empty default.

**Comment by lorensr** [comment]
In the meantime, how do I fix? Tried reinstalling, still get the error on
all commands 😄

[image: image.png]

**Comment by feedmeapples** [comment]
if that's a quick fix i'll send a PR. Meanwhile feel free to delete the config `~/.config/temporalio/temporal.yaml`

**Comment by lorensr** [comment]
Deleting worked, thanks!
