### ISSUE TITLE
Apply markdown processing to --help definitions

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/cli#305]
### Is your feature request related to a problem? Please describe.

--help Definition texts output markdown links as plain text, making them hard to read

### Describe the solution you'd like

We apply markdown to text processor for Usage texts. Make the same for Definitions https://github.com/temporalio/cli/blob/36afc181974f4a77fca287b432a457657a249bcc/helpprinter/helpprinter.go#L42C10-L42C21

**Comment by josh-berry** [comment]
Duplicate of #151
