### ISSUE TITLE
Ability to set authorization via Envar

### ISSUE THREAD

**Issue by Smithx10** [temporalio/cli#342]
In tctl we can set TEMPORAL_CLI_AUTH="Bearer $token",  in temporal cli from my quick look we have to continuously use ```--grpc-meta```. 

From common/flags.go I couldn't find any way to set such a thing.

```go
	&cli.StringSliceFlag{
		Name:     FlagMetadata,
		Usage:    FlagMetadataDefinition,
		Category: CategoryGlobal,
	},
```

**Comment by josh-berry** [comment]
Duly noted, will keep this in mind for a future release!

**Comment by metavee** [comment]
It would be great to see this implemented! It's not ideal to be passing credentials back and forth on the command line.

**Comment by josh-berry** [comment]
@cretz is planning to add a --api-key option that will have an associated environment variable in #478, so we can probably drop this one in favor of that.
