### ISSUE TITLE
[Feature Request] using `operator update` in wrong order should trigger error, not silently do nothing

### ISSUE THREAD

**Issue by karelbilek** [temporalio/cli#345]
### Is your feature request related to a problem? Please describe.

I did, by mistake, in script

`temporal operator namespace update default --retention 5`

instead of 

`temporal operator namespace update --retention 5 default`.

It's an understandable error to make.

Instead of the command failing, or at least mentioning something might be wrong, the command just writes

`Namespace default successfully updated.`

### Describe the solution you'd like

When the order is wrong, command should return an error (exit code 1) and write something.

It's hard to say how it should detect that. If by detecting an errorneous option, or by seeing that nothing got updated.

### Additional context

I also made a PR for docs here

https://github.com/temporalio/documentation/pull/2345

**Comment by josh-berry** [comment]
related: https://community.temporal.io/t/unable-to-update-namespaces-using-temporalio-cli/8771/2?u=josh-berry

**Comment by josh-berry** [comment]
Looks like this issue got reported twice in a short timeframe. I'll mark this one as a duplicate to #347, which is more general (unfortunately, it's every command, not just `operator namespace update`). But you are absolutely right this should at minimum throw an error, or at least accept the option, and not silently ignore the option. Sorry for the trouble!

**Comment by karelbilek** [comment]
Oh that's totally fine, you're right the other is more general
