### ISSUE TITLE
[Bug] Arguments cannot be used out of order, but do not report any error.

### ISSUE THREAD

**Issue by askreet** [temporalio/cli#347]
### What are you really trying to do?

I am trying to use `temporal operator namespace create` to create a namespace in a remote cluster using `--env`.

### Describe the bug

The following command works:

`temporal operator namespace --env my-env create new-namespace-name`

The following command silently ignores `--env` and uses the default localhost cluster:

`temporal operator namespace create new-namespace-name --env my-env`

### Minimal Reproduction

1. Configure an env to point to a remote cluster.
2. Use the `--env` flag in the tail position. Watch it be ignored.

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 0.10.5 (server 1.21.4) (ui 2.17.0)
- Are you using Docker or Kubernetes or building Temporal from source? Local CLI, docker Server and remove Server.

### Additional context

FWIW, my preference would be for the tail position `--env` to _work_, but if it's not going to it should tell me it's an invalid flag or in an invalid position, rather than silently accepting it.

**Comment by lorensr** [comment]
> my preference would be for the tail position --env to work

Mine as well!

**Comment by josh-berry** [comment]
This should be done in 0.12.
