### ISSUE TITLE
[Bug] -input-file option not working with multiple JSON objects in the file

### ISSUE THREAD

**Issue by jdntra30** [temporalio/cli#351]
### What are you really trying to do?

Trying to run a new workflow with the input-file flag. It works with one input, but encounters an issue for multiple inputs.

### Describe the bug

In the documentation for input-file flag, it says: "Passes optional input for the Workflow from a JSON file. If there are multiple JSON files, concatenate them and separate by space or newline. Input from the command line will overwrite file input."

So our python script creates a file with two JSON objects:
{ "key1" : "value1"} {"key2" : "value2"}

I tried with both space character and newline character. It doesn't work. It only works with one input.

With two inputs, I get this error: **"Error: input is not valid JSON: invalid character '{' after top-level value"**

### Environment/Versions

- OS and processor: Mac OS Ventura 13.4
- Temporal Version: Tried with both temporal version 0.10.6, and tctl version next
- Are you using Docker or Kubernetes or building Temporal from source? Docker with tctl. Built with the direct source for Temporal

**Comment by josh-berry** [comment]
Sorry about that!

The docs are unfortunately just wrong about how `--input-file` works, and it seems we missed handling multiple arguments entirely. :/ I have a fix pending that allows for passing multiple `--input-file` options to pass distinct arguments (one per file), and clarifies in the help output how this works.
