### ISSUE TITLE
[Bug] When doing describe of namespace metadata not displayed 

### ISSUE THREAD

**Issue by nitishnigam1989** [temporalio/cli#363]
### What are you really trying to do?

I've updated my namespace with data using temporal cli v0.10.6 but when doing describe its not getting displayed

`
$ /c/Nitish/Softwares/temporal_cli_0.10.6_windows_amd64/temporal.exe operator namespace update --description "test namespace" --data k8s_namespace=temporal-dev --data env=dev test-ns6  

Namespace test-ns6 update succeeded.  

$ /c/Nitish/Softwares/temporal_cli_0.10.6_windows_amd64/temporal.exe operator namespace describe test-ns6  

  NamespaceInfo.Name                    test-ns6
  NamespaceInfo.Id                      3408f0ab-ff23-4023-aea4-d7208066cc4b
  NamespaceInfo.Description             test namespace
  NamespaceInfo.OwnerEmail
  NamespaceInfo.State                   Registered
  Config.WorkflowExecutionRetentionTtl  72h0m0s
  ReplicationConfig.ActiveClusterName   active
  ReplicationConfig.Clusters            [&ClusterReplicationConfig{ClusterName:active,}]
  Config.HistoryArchivalState           Disabled
  Config.VisibilityArchivalState        Disabled
  IsGlobalNamespace                     false
  FailoverVersion                                                                      0
  FailoverHistory                       []
`
But if i do describe using tctl , it shows the respective metadata

`$ ~/go/bin/tctl.exe --ns test-ns6 n desc  

Name: test-ns6
Id: 3408f0ab-ff23-4023-aea4-d7208066cc4b
Description: test namespace
OwnerEmail:
NamespaceData: map[string]string{"env":"dev", "k8s_namespace":"temporal-dev"}
State: Registered
Retention: 72h0m0s
ActiveClusterName: active
Clusters: active
HistoryArchivalState: Disabled
IsGlobalNamespace: false
FailoverVersion: 0
FailoverHistory: []
VisibilityArchivalState: Disabled
Bad binaries to reset:
+-----------------+----------+------------+--------+
| ←[94mBINARY CHECKSUM←[0m | ←[94mOPERATOR←[0m | ←[94mSTART TIME←[0m | ←[94mREASON←[0m |
+-----------------+----------+------------+--------+
+-----------------+----------+------------+--------+`

### Describe the bug

Describe of namespace using temporal cli doesn't show the NamespaceData

### Environment/Versions

- OS and processor: Windows
- Temporal Version: 1.20.4 
- Temporal CLI version : 0.10.6
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by josh-berry** [comment]
Thanks for letting us know. Looks like an easy fix.
