### ISSUE TITLE
[JWT Token] Add environment variable for JWT Token

### ISSUE THREAD

**Issue by andreclaro** [temporalio/cli#370]
### Is your feature request related to a problem? Please describe.

Right now we need to pass `--grpc-meta` option in every single command with the JWT Token.

Example:
```
temporal operator namespace list --grpc-meta "Authorization=Bearer $TOKEN"  

temporal workflow list --grpc-meta "Authorization=Bearer $TOKEN" --namespace namespacename

````

### Describe the solution you'd like

Add environment variable for JWT Token so we don't need to be always passing `grpc-meta` option to the CLI.

```
TEMPORAL_JWT_TOKEN="..."

temporal operator namespace list

temporal workflow list  --namespace namespacename
```

**Comment by bergundy** [comment]
This would be a `TEMPORAL_GRPC_META` env var that supports multiple values.
