### ISSUE TITLE
[Feature Request] Add retirability to `task-queue describe`

### ISSUE THREAD

**Issue by lorensr** [temporalio/cli#392]
### Is your feature request related to a problem? Please describe.

I like the UI version of task queue info:

![image](https://github.com/temporalio/cli/assets/251288/6d3b7a40-a3c8-4e6e-9327-029c4f1f624a)

and folks might look for "retirability" info in the CLI and not find it, and for others, "retirability" might make more sense than "reachability".

At the moment, you need to run a separate command, `task-queue get-build-id-reachability`, and finding it requires knowing something named "get-build-id-reachability" is related to versioning and retirability.

### Describe the solution you'd like

A `retirability` column in `task-queue describe`

**Comment by josh-berry** [comment]
@antlai-temporal This seems like it might be an old versioning ticket; is it still relevant or can we close it?

**Comment by josh-berry** [comment]
Closing since I never heard back. @antlai-temporal please reopen if still relevant to Versioning.
