### ISSUE TITLE
[Bug] Incorrect "paused" status for schedules

### ISSUE THREAD

**Issue by jmdacruz** [temporalio/cli#416]
### What are you really trying to do?

Use `temporal schedule list` to get the current status of schedules, specifically if they are paused or not.

### Describe the bug

Given a schedule ID that is paused (as shown by the Temporal UI), running `temporal schedule list` shows the same schedule ID with a value of "false" for the "Paused" column. The Schedule ID is clearly paused, so the UI is presenting the correct status, but the CLI is not (value for this column should be "true").

I can run `temporal schedule toggle --unpause` or `--pause` and this will correctly affect the schedule (the schedule starts/stops, with the UI reflecting the correct status), but the CLI is always showing "false" for the "Paused" column.

I'm reporting this on the CLI, given that the UI seems to be properly showing this status.

### Environment/Versions

- OS and processor: Linux
- Temporal CLI Version: Reproducible with CLI v0.10.5 and v0.10.7
- Temporal Version: 1.20.0
- Temporal UI: 2.15.0

**Comment by dnr** [comment]
My guess is that the difference isn't UI vs CLI, but list vs describe. Does the CLI report the incorrect result for `temporal schedule describe` also? And does the UI show the correct state in the schedules list (not individual schedule details view)?

What visibility store are you using, and are you using standard or advanced?

**Comment by jmdacruz** [comment]
you nailed it on both @dnr: `temporal schedule describe` reports the correct value, and the UI list shows the schedule incorrectly as "running", but the individual details view shows it correctly as paused.
We are using only Cassandra for now.

**Comment by dnr** [comment]
Schedule metadata in the list view requires advanced visibility. If you're using cassandra, you'll have to use elasticsearch as well. This will be required starting in 1.24, I believe.

It's true that the CLI and UI should display no data in that case, instead of "paused: false". But considering this will soon be an unsupported configuration, I doubt we're going to get to fix this.

**Comment by jmdacruz** [comment]
In that case, let's close this issue. Thanks @dnr !
