### ISSUE TITLE
Updating Schedule with memo option not updating memo

### ISSUE THREAD

**Issue by 4ndypanda** [temporalio/cli#433]
### Describe the bug

Doing `temporal schedule update --schedule-id ... --memo $KEY=$VALUE` does not update the memo of the Schedule.

### Minimal Reproduction

```
# Create Schedule
temporal schedule create --schedule-id foo --workflow-type Foo --task-queue default --memo bar=1

# Describe Schedule shows "Memo" with "bar": "1"
temporal schedule describe -schedule-id foo -o json

# Update Schedule
temporal schedule update --schedule-id foo --workflow-type Foo --task-queue default --memo bar=2

# Describe Schedule still shows "Memo" with "bar": "1" instead of "bar": "2"
temporal schedule describe -schedule-id foo -o json
```

### Environment/Versions
Running in Docker with this version
```
$ temporal -v
temporal version 0.10.7 (server 1.22.2) (ui 2.21.3)
```

### Additional context
Is there also any way to get the memo returned with `temporal schedule list`? Some SDKs like the Python one returns memo in the list results: https://python.temporal.io/temporalio.client.ScheduleListDescription.html#memo.

**Comment by dnr** [comment]
Updating search attributes and memos on schedules isn't supported yet. See https://github.com/temporalio/temporal/issues/4858 (that's about search attributes but they're handled very similarly so we'll do memo at the same time)

**Comment by dnr** [comment]
For memo in list results, it's available in the protocol but correct, not exposed in the cli yet. That should be easy to add.

**Comment by Sushisource** [comment]
Depends on https://github.com/temporalio/cli/pull/459 / could possibly be done there
