### ISSUE TITLE
[Bug] Inconsistent Encoding Behavior in CLI Commands

### ISSUE THREAD

**Issue by ndtretyak** [temporalio/cli#437]
### Describe the bug

There appears to be an inconsistency in how the Temporal CLI commands handle JSON payloads. The `workflow start/signal/etc` commands use the `UnmarshalInputsFromCLI` function to parse provided JSON payloads. Subsequently, these JSON payloads are correctly encoded back by the `defaultEncoder`.

However, the `activity complete` command behaves differently. It attempts to encode the `--result` flag directly, which is a string. As a result, the payload ends up as a JSON-encoded string (e.g., `\"{}\"`) rather than a simple JSON object (e.g., `{}`).

https://github.com/temporalio/cli/blob/7267df668277a9b43c50d454af50ff5e2b9f8e90/activity/activity_commands.go#L30

**Comment by Quinn-With-Two-Ns** [comment]
This should be addressed in the CLI [rewrite](https://github.com/temporalio/cli/tree/cli-rewrite) as payload encoding is totally rewritten to ensure consistency.
