### ISSUE TITLE
[CLI Refresh] Output valid JSON and/or JSONL for `workflow list`

### ISSUE THREAD

**Issue by dandavison** [temporalio/cli#448]
Commands such as `workflow list` conceptually output a sequence of objects. Currently `cli-rewrite` JSON output is formatting this as a sequence of multiline JSON objects. This means that the overall result (when there is >1 workflow) is neither valid JSON nor valid [JSONL](https://jsonlines.org/).

A natural requirement is that the CLI should produce either valid JSON or valid JSONL. Possible designs satisfying that requirement:

### A

- `--output json` always produces valid JSON (i.e. we add `[`, commas, and `]` to the `workflow list` output).
- We will also support `--output jsonl` meaning: convert all top-level arrays to newline-separated objects; otherwise do not emit any newlines in JSON.

  Thus `--output jsonl` would apply consistently to all commands (but mainly be useful for commands such as `workflow list` and `env get` that produce top-level arrays, although people could conceivably use it to produce compact output for other commands).

### B

- `--output json` produces valid JSON everywhere except for certain commands (perhaps only `workflow list`) where it produces valid JSONL.

  The only change required here would be eliminating the newlines within `workflow list` items. A downside here is that it will no longer be possible to produce easily human-readable output from `workflow list` without piping into something like `jq`.

**Comment by cretz** [comment]
`batch list` seems to apply here too

**Comment by cretz** [comment]
`cluster list` seems to apply here too (though not really, it should probably be a fixed list since it'll never be big)

**Comment by cretz** [comment]
`operator namespace list` seems to apply here too (though not really, it should probably be a fixed list since it'll never be big)

**Comment by cretz** [comment]
Ok, after discussion, it looks like we're going with Option A here

**Comment by cretz** [comment]
Option A complete
