### ISSUE TITLE
[Bug] Decide on --name vs --type and use consistently.

### ISSUE THREAD

**Issue by dandavison** [temporalio/cli#475]
From https://github.com/temporalio/cli/pull/455#discussion_r1501713227

> In our current (0.x) `temporal` CLI, signal and update use `--name` whereas query uses `--type`.  However, IMO we need the flag name to be the same for signal, query, and update, so a compatibility break with 0.x is inevitable.

**Comment by lorensr** [comment]
Current CLI matches the gRPC API terminology. 

Docs uses `name` for both Query and Signal, nothing for Update yet. 

Inclined toward using `name` for all 3 in docs & CLI.

**Comment by cretz** [comment]
> Inclined toward using name for all 3 in docs & CLI.

Same and we've done this for newer SDKs. We would have to decide this now pre-1.0. Query is pretty commonly used so this would be our biggest compatibility break to date I believe, but at least (with `--type` removed) it'd be an immediately CLI flag validation failure.

**Comment by Sushisource** [comment]
We could make them aliases for each other potentially.

Personally I think `type` is slightly more accurate, but, honestly either works.
