### ISSUE TITLE
[Bug] Using --input in a windows terminal

### ISSUE THREAD

**Issue by svickers** [temporalio/cli#477]
### What are you really trying to do?

Trying to pass input values to start a workflow.

### Describe the bug

When using a command from the docs like this:
```sh
temporal workflow start --task-queue greeting-tasks --type GreetSomeone --namespace default --input '"joe"'
```
Receiving the error:
```
Error: input is not valid JSON: invalid character 'j' looking for beginning of value
```

![Screenshot_87](https://github.com/temporalio/cli/assets/105884/2ce57754-26d9-4d81-a096-ac6bf9b55439)

### Workflow 

```py
from datetime import timedelta
from temporalio import workflow

@workflow.defn
class GreetSomeone:
    @workflow.run
    async def run(self, name: str) -> str:
        return f"{name}"

```

### Environment/Versions

- OS and processor: Windows 11
- Temporal Version: 0.10.7 (server 1.22.2) (ui 2.21.3)

**Comment by cretz** [comment]
You have to use Windows quote escaping, e.g. `--input """joe"""`. This is not related to Temporal, this is a general Windows approach on how to have quotes in parameters.

(closing as question not bug, but feel free to continue commenting or join us on https://t.mp/slack or in our forums)
