### ISSUE TITLE
Support for WorkflowIdConflictPolicy

### ISSUE THREAD

**Issue by josh-berry** [temporalio/cli#528]
See https://github.com/temporalio/features/issues/437

**Comment by stephanos** [comment]
NOTE: Please don't forget SignalWithStart API.

**Comment by yuandrew** [comment]
@stephanos I am starting to look at this, I'm not seeing the CLI interact with any SignalWithStart API, can't find any references to SignalWithStart in the entire CLI codebase. Could I be missing something?

**Comment by cretz** [comment]
Signal with start needs to be in the CLI (https://github.com/temporalio/cli/issues/353), but until it's there, yeah this only applies to start (and maybe schedule, didn't check).
