### ISSUE TITLE
[Feature Request] CLI rewrite needs to support "pretty" log format and log level for older SDKs

### ISSUE THREAD

**Issue by cretz** [temporalio/cli#533]
### Describe the solution you'd like

All SDKs basically expect `server start-dev` to be able to set `--log-format` to something like `"pretty"` and `--log-level` to a needed value ([Go](https://pkg.go.dev/go.temporal.io/sdk/testsuite#DevServerOptions), [TS](https://typescript.temporal.io/api/interfaces/testing.DevServerConfig#log_), [Python](https://python.temporal.io/temporalio.testing.WorkflowEnvironment.html#start_local), [.NET](https://dotnet.temporal.io/api/Temporalio.Testing.DevServerOptions.html#Temporalio_Testing_DevServerOptions_LogFormat), [Core](https://github.com/temporalio/sdk-core/blob/409e74ec8e80ae4c1f9043e8b413b1371b65f946/core/src/ephemeral_server/mod.rs#L139), etc). Today we have no concept of `--log-format` of "pretty", just `text` and `json`, and we have no concept of `--log-level` for just server, we have `--log-level-server` which we intentionally separated because we want `warn` the default there.

Suggestion: Add `pretty` as an alias for `text` in `--log-format`, and change `--log-level-server` to default to `--log-level` if not set, and change `--log-level` default for _just this command_ to `warn`.

**Comment by josh-berry** [comment]
Your suggestion seems fine to me. 👍

**Comment by cretz** [comment]
Done in #535
