### ISSUE TITLE
[Bug] TEMPORAL_ENV may not be working

### ISSUE THREAD

**Issue by cretz** [temporalio/cli#541]
### Describe the bug

Confirm `TEMPORAL_ENV` env var properly sets the equivalent of `--env`. This may require special handling since that flag is used before others (because it governs what the other flags have to be).

**Comment by josh-berry** [comment]
Took a quick look at the code and [preprocessOptions()](https://github.com/temporalio/cli/blob/f806427a06f251f38e74ca34608484d1d08ccc45/temporalcli/commands.go#L110) does not appear to check the environment variable, but looks directly at the command line arguments. So I think this is an implementation oversight.

(We should probably have more testing around `--env` in general I think; I noticed another regression around `temporal env delete` I'll have to either fix or write up properly tomorrow.)
