### ISSUE TITLE
[Feature Request] `temporal schedule update` with `--calendar` option to support multiple calendars

### ISSUE THREAD

**Issue by petrkoutnycz** [temporalio/cli#557]
### Is your feature request related to a problem? Please describe.

Currently the `temporal schedule update` command support setting of a single calendar only which is limiting. If I try to provide an array of them instead, it fails with JSON deserialization.

### Describe the solution you'd like

I would like the `update` command to support setting an array of calendars. I.e. `--calendar` can take an array with JSON definitions.

**Comment by petrkoutnycz** [comment]
Will try, thanks!

**Comment by cretz** [comment]
This is the recommended way to provide multiple of these values. Let us know if it works well for you and we'll close this issue.

**Comment by petrkoutnycz** [comment]
Oh crap, it works. Shame on me. Thank you 🙏
