### ISSUE TITLE
[Feature Request] Fail if provided `--env`/`TEMPORAL_ENV` is unknown

### ISSUE THREAD

**Issue by cretz** [temporalio/cli#566]
### Describe the solution you'd like

We _think_ we want to fail users if they provide an env that isn't there. Discussion points:

* What did pre-0.12.0 versions do?
* Do we want to fail or warn? We think we want to fail but could be big compat break from above bullet if we never did before.
* What if the env exists but is empty? Should we start removing empty envs from the config when their last value is removed?
* Make clear in the error what is invalid just in case it's some leftover `TEMPORAL_ENV` env var that has a bad value

**Comment by josh-berry** [comment]
We should make sure not to break `temporal env` commands when we do this, because `temporal env set --env ...` can be used to create new environments.

**Comment by Sushisource** [comment]
Confirmed that the old CLI does break on unknown envs, so will be fixing.
