### ISSUE TITLE
[Bug] Improve CLI errors when namespace is incorrect

### ISSUE THREAD

**Issue by robzienert** [temporalio/cli#589]
### What are you really trying to do?

Any action in the CLI that involves specifying a namespace.

### Describe the bug

When an incorrect namespace is provided, the CLI returns a pretty unhelpful error message similar to: `Error: unable to run workflow: context deadline exceeded`. Unfamiliar users to Temporal will not look to see if they're providing the correct namespace, and instead escalate to a central team to debug.

### Minimal Reproduction

Run a command that requires taking `-n` namespace flag, but provide it a namespace that does not exist.

### Environment/Versions

I think this is global behavior.

**Comment by josh-berry** [comment]
Hi @robzienert, can you tell me which specific commands you've observed this with? I've tried with a couple different commands (e.g. `temporal operator namespace describe` and `temporal workflow describe`) and they all return `namespace not found` or similar errors. Thanks!

**Comment by josh-berry** [comment]
I'm also unable to reproduce this with `workflow start` and `workflow execute`:

```
❯ temporal workflow execute -n asdf --task-queue q --type foo
time=2024-06-18T16:41:09.619 level=ERROR msg="failed starting workflow: Namespace asdf is not found."

❯ temporal workflow start -n asdf --task-queue q --type foo
time=2024-06-18T16:41:14.306 level=ERROR msg="failed starting workflow: Namespace asdf is not found."
```

So to make any progress I'm going to need an example showing which command is at issue. Thanks!

**Comment by josh-berry** [comment]
Closing since I haven't heard back.

@robzienert If you're still seeing this in the latest version of the CLI (v0.13.1), please feel free to reopen, and let us know:

- Exactly which command you were running that caused this
- Which server you're running against (the dev-server? an on-prem setup? Temporal Cloud?) and which version of the server (if you know)
