### ISSUE TITLE
[Feature Request] Enable Tab Completion

### ISSUE THREAD

**Issue by badideasforsale** [temporalio/cli#61]
### Describe the solution you'd like

It would make `tctl` more useful and discoverable if it supported tab-completion.

For example, instead of having to laboriously type all the characters in
```
tctl workflow list
```

It would be nicer if instead:
```
tctl wo[TAB] l[TAB]
```
resulted in the same thing.

This would also make it easier to see all the options `tctl` provides, instead of needing to frequently
refer back to the documentation webpage for flags, options, and all the rest. `tctl [TAB]` could produce:
```
$ tctl
    activity
    admin
    batch
    cluster
    dataconverter   
    namespace
    task queue
    workflow
```

### Additional context

Other command-line programs offer this sort of functionality. I have no strong opinions about how this is implemented or displayed or anything. It would improve the user experience when interacting with the tool.

**Comment by feedmeapples** [comment]
This is added in the latest versions of Temporal CLI (and tctl)
