### ISSUE TITLE
[Feature Request] Support query for temporal schedule list

### ISSUE THREAD

**Issue by dnr** [temporalio/cli#616]
Support query for `temporal schedule list` using this new field: https://github.com/temporalio/api/blob/6cd92a2f214a2d14872af81e31b6eee2f8b745ca/temporal/api/workflowservice/v1/request_response.proto#L1157

**Comment by cretz** [comment]
This is actually needed everywhere, not just CLI. Opened https://github.com/temporalio/features/issues/505.
