### ISSUE TITLE
[Bug] Invalid workflow list query

### ISSUE THREAD

**Issue by lorensr** [temporalio/cli#63]
### What are you really trying to do?

```
temporal workflow list -q "ExecutionStatus != 'foo'"
Error: unable to list workflow executions: invalid query: unable to convert filter expression: operator '!=' not allowed in comparison expression
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

### Environment/Versions

- OS and processor: Mac
- Temporal Version: 0.2.0 (homebrew)

**Comment by lorensr** [comment]
Maybe != requires advanced visibility, so won't work until SQL adv vis is shipped?

**Comment by cretz** [comment]
I bet this is true, may have to wait.

**Comment by feedmeapples** [comment]
i'm seeing that `temporal workflow list -q 'ExecutionStatus!="Completed"'` works now with 1.20

however for specifically status "foo" just getting context deadline exceeded

**Comment by lorensr** [comment]
Weird, maybe @rodrigozhou knows why?

**Comment by rodrigozhou** [comment]
I found the issue. The error was supposed to be non-retryable because `'foo'` is an invalid value for `ExecutionStatus`, but it's currently retrying until the request times out.

PR fixing the issue: https://github.com/temporalio/temporal/pull/4036
