### ISSUE TITLE
[Feature Request] Obtain parity for "tctl adm cluster list_gossip" in temporal CLI

### ISSUE THREAD

**Issue by sahilvv** [temporalio/cli#631]
### Is your feature request related to a problem? Please describe.

legacy temporal CLI (tctl) had ability to run command to obtain gossip information to debug cluster health. This is requiring us to still rely on tctl which is on the deprecation path. 

### Describe the solution you'd like

Obtain equivalent command support to "tctl adm cluster list_gossip"

### Additional context
N/A

**Comment by cretz** [comment]
We have removed advanced self-hosted `admin` commands in the CLI in favor of using the `tdbg` CLI. I believe, using the `admin-tools` container, this can be done with `tdbg` via `tdbg membership list-gossip`.
