### ISSUE TITLE
[Feature Request] Add information about server build to `start-dev` banner

### ISSUE THREAD

**Issue by dandavison** [temporalio/cli#635]
I'd like to see info about the commit hash of Server that it has been built against, if go tooling makes that possible. (From brief investigation it seemed that `go list -json -m go.temporal.io/server` did not contain that information when a local `replace` is in effect.)

**Comment by josh-berry** [comment]
In released versions, you can always get to the commit hash by going via the Server's version tag, which is printed in the output of `temporal --version`. Is this not sufficient?

**Comment by dandavison** [comment]
I'd like developers who build the CLI against a local server commit to be able to discover from the CLI what commit it has been built against.

**Comment by cretz** [comment]
In Go you don't really get to add steps to build like this. We use the server like a library and we count on https://pkg.go.dev/go.temporal.io/server/common/headers#ServerVersion to be accurate. Technically we may be able to use https://pkg.go.dev/runtime/debug0#ReadBuildInfo to get the version of the dependency, but it'll be Go version format, which will only have what's in `go.mod`.

**Comment by dandavison** [comment]
OK, so then the feature request is to make it possible for an interested developer to script their own custom build process that will produce a binary that can emit information (preferably in the startup banner) about the server commit SHA that was used in the build.

**Comment by josh-berry** [comment]
Sorry, but I'm still trying to understand why this would be helpful? To get a build on a non-released server in the first place, you have to specify the specific commit hash you want in `go.mod` before doing the build. So if you forget what commit you used, you need only look at `go.mod` and it will tell you.

I can see how having it baked into the binary itself might be useful if you keep random binaries lying around outside the source tree, but is that really a common use case? I can't think of a time I've needed to do that, myself, but maybe I'm missing something.

**Comment by cretz** [comment]
If a user wanted to put their own version in, I think you can have `-ldflags` on `go build` with something like `-X "github.com/temporalio/cli/temporalcli.Version=v1.2.3"` (this is what we have goreleaser do) but may not work for `-X "go.temporal.io/server/common/headers.ServerVersion=v1.2.3"` because that's a const.

**Comment by dandavison** [comment]
Implemented in #637 

> To get a build on a non-released server in the first place, you have to specify the specific commit hash you want in go.mod before doing the build. So if you forget what commit you used, you need only look at go.mod and it will tell you.

Actually, that's not true: it's common to do something like

```go
replace go.temporal.io/server => ../temporal
```

That's the main reason that this feature makes sense: when you do that you have no record of what commit was used.

> I can see how having it baked into the binary itself might be useful if you keep random binaries lying around outside the source tree, but is that really a common use case? I can't think of a time I've needed to do that, myself, but maybe I'm missing something.

Although the above is sufficient reason, I  think it's also useful even if you have an explicit commit hash in go.mod. During development operations by Temporal engineers, it's common to use `temporal server start-dev` while working in many different repositories: CI/CD, SDKs, samples repos, features repo, etc. Sometimes, people need to work on a non-released server version. But in this scenario, the CLI repo is not on your mind, and it's not where your currently working. It's much more convenient to just have the server startup banner print out the server branch it was built against, than to have to switch context, `cd` to the CLI repo and double-check a commit hash that might be lying around in uncommitted changes to go.mod. 


> If a builder of the exe wanted to put their own CLI version in, I think you can have -ldflags on go build

Thanks @cretz -- I didn't see your comment until not but that's what I've done in #637.

**Comment by dandavison** [comment]
As an one more motivation, it's common to want to compare the behavior of different binaries when debugging or investigating performance issues. While of course one can give the binaries different file names indicating how they differ, it would less error-prone to write that info into the version string to make sure there's no confusion during your experiments.
