### ISSUE TITLE
[Bug] Creating schedule with CLI - unknown flag: --workflow-type

### ISSUE THREAD

**Issue by VincentWillats** [temporalio/cli#639]
### What are you really trying to do?

Create a schedule

### Describe the bug

When trying to create a schedule when following the `temporal schedule create --help` example ([or the docs](https://docs.temporal.io/cli/schedule#create))

```
Create a new Schedule on the Temporal Service. A Schedule automatically starts
new Workflow Executions at the times you specify.

For example:

  temporal schedule create \
    --schedule-id "YourScheduleId" \
    --calendar '{"dayOfWeek":"Fri","hour":"3","minute":"30"}' \
    --workflow-id YourBaseWorkflowIdName \
    --task-queue YourTaskQueue \
    --workflow-type YourWorkflowType
```

I get `unknown flag: --workflow-type`

### Minimal Reproduction

```
  temporal schedule create \
    --schedule-id "YourScheduleId" \
    --calendar '{"dayOfWeek":"Fri","hour":"3","minute":"30"}' \
    --workflow-id YourBaseWorkflowIdName \
    --task-queue YourTaskQueue \
    --workflow-type YourWorkflowType
```

### Environment/Versions

temporal version 1.0.0 (Server 1.24.2, UI 2.28.0)

### Additional context

Looks like `--type` works, but `--workflow-type` does not.

**Comment by josh-berry** [comment]
Oops, you're right, this is a typo in the example, it should be `--type`. Thanks for pointing it out and sorry for the confusion!
