### ISSUE TITLE
[Feature Request] Add reset reapply to batch reset command

### ISSUE THREAD

**Issue by jamipouchi** [temporalio/cli#701]
### Is your feature request related to a problem? Please describe.
I have found myself wanting to batch reset workflows without reapplying signals, unable to do so with temporal cli. It is possible with sdk code, and with tctl, which makes it look like someone forgot to add it.

### Describe the solution you'd like
Add reset reapply options to the batch reset command.

### Additional context
I have [opened a pr](https://github.com/temporalio/cli/pull/700) solving it.

**Comment by josh-berry** [comment]
PR is merged and is part of the 1.1.2 release. Closing.
