### ISSUE TITLE
[Feature Request] reset should not require workflowid if runid is provided

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/cli#710]
https://github.com/temporalio/cli/blob/main/temporalcli/commands.workflow_reset.go#L33

currently reset requires workflow id and if not present seems to fall back to batch reset
request is to also check presence of runid and if provided not to require workflow id, before falling to batch reset

**Comment by cretz** [comment]
Hrmm, all specific-workflow operations require a workflow ID, but they can also provide run ID if they want. Are you saying that this specific-workflow operation should be unique in that it doesn't require workflow ID?

**Comment by cretz** [comment]
Makes sense. To confirm we require workflow ID for all workflow-specific operations and _also_ allow run ID if the user wants. It makes sense that if workflow ID is _not_ present, we should fail if run ID _is_ present.

**Comment by josh-berry** [comment]
@tsurdilo Can you give me an example command that's accepted but shouldn't be?

It looks like we already fail reset commands if workflow ID is provided but run ID isn't:

https://github.com/temporalio/cli/blob/dd3072a5dc1baa4d105b7ce2ea8b0225a4fb632c/temporalcli/commands.workflow_reset.go#L57

**Comment by cretz** [comment]
> It looks like we already fail reset commands if workflow ID is provided but run ID isn't

I had understood the issue as us not properly failing if a run ID only is provided. But I may have misunderstood.

**Comment by cretz** [comment]
While run ID is often globally unique, I am not aware of any workflow-specific operation where we've ever accepted run ID without a workflow ID. I think we should always fail if a workflow ID is missing for a workflow-specific call (so if run ID is present here without workflow ID, we should fail IMO). However, if this is something unique to update we need to support, we should first confirm this works on the server, then we can discuss if we even want this. I am not sure we do.

**Comment by josh-berry** [comment]
👍 Would like to hear what @tsurdilo had in mind for a use case / context about why this is needed. But if there's not a compelling reason then I agree with closing.

**Comment by josh-berry** [comment]
Closing since I never heard back. @tsurdilo please feel free to re-open if you've got an example like I requested above.
